# Generated by Django 3.2.6 on 2021-08-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_alter_inquiry_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
