# Generated by Django 3.2.6 on 2021-08-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_max_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='max_price',
            field=models.IntegerField(blank=True, editable=False),
        ),
    ]
