# Generated by Django 3.2.6 on 2021-08-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_max_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='max_price',
            field=models.IntegerField(auto_created=True, blank=True, null=True),
        ),
    ]
